### ISSUE TITLE
Can not get route name with useRoute hook

### ISSUE THREAD

**Issue by fayeah** [vuejs/vue-router-next#1109]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/aged-architecture-doo43?file=/src/main.js)

### Steps to reproduce
get route name inside setup method with useRoute hook, then refresh the page, name is undefined:
```
 const route = useRoute();
 console.log("route", route.name);
```

### What is expected?
can get the name

### What is actually happening?
name is undefined

---
I checked the route info, and have set the name for each route. tried `onBeforeRouteUpdate` hook inside setup method, it's event not evoked. not sure why, please help to figure it out.

**Comment by posva** [comment]
This is expected and has been answered in multiple issues before. It's because the navigation is asynchronous so `route` is updated after `created` with the actual name. You can use a navigation guard or watcher for this purpose but ideally, passing the route.name in a declarative way is better.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by fayeah** [comment]
oh, yeah, I thought this is the place where we raise questions, but thanks for your kind answers.
