### ISSUE TITLE
Cannot use component with css 

### ISSUE THREAD

**Issue by riderx** [vuejs/vue-router-next#1233]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/festive-fast-6somo?file=/src/components/about.vue)

### Steps to reproduce
you can find a codesandbox: 
https://codesandbox.io/s/festive-fast-6somo?file=/src/components/about.vue
and the issue reported to vue-tel-input who have issue with vue-router :
https://github.com/iamstevendao/vue-tel-input/issues/310

### What is expected?
It should work like when not router used

### What is actually happening?
it break the compilation step

**Comment by posva** [comment]
The codesandbox works... In any case, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro when reporting a bug. Open a new issue without vue-tel-input if you manage to reproduce it

**Comment by riderx** [comment]
@posva yes the codesandbox work until you uncomment the code in about component, then nothing work anymore.

the issue happen only when combining `vue-tel-input` module, so I cannot remove it, it's the bare minimal, I have read and follow that.
I edited to let you see better the error, I'm sorry I didn't think to copy the content of the original issue, made in vue-tel-input.
I hope that more clear

**Comment by riderx** [comment]
@posva it took me 3 hours to understand and find a way to reproduce it in codesandbox with webpack.

In my stack : vue 3 with vite and setup script in ts, until now it's impossible to run it in codesandbox.

I did a huge work to allow you to test it, more than just a text or screenshot, and you close direct the issue.

I understand you receive a lot of noise, and a lot of people just ask the wrong things, like me it seems.

But closing the issue straight do look **rude**, even you say "please read and follow the rules".
I do think a bit more of empathy will help all of us collaborate better.

Like the last thread of @gaearon where he explains why he value a lot people who took time to make him save it.

I don't see the world by your eyes, but if you take time to share what you live, i will, like many other people who would love to help better.

We gonna improve and make your life easier.

For most people interacting with a big Open-source project means been slap in the face to learn, no-one don't need that. 
that the way to make the tech more inclusive, in my opinion.

**Comment by posva** [comment]
> I do think a bit more of empathy will help all of us collaborate better.

I really think you should read yourself and realize the weight you are putting on a maintainer's shoulders when you say something like _it took me 3 hours to understand (...)_... does it help the maintainer understand the issue? It's more like trying to make them feel guilty for wasting your time. I do not appreciate that, even less when **you ask for empathy**.

>  even you say "please read and follow the rules".

I send you to https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro because minimal means no external libraries and we repeat **so much** we literally put up a page for it.

> more than just a text or screenshot, and you close direct the issue.

<img width="822" alt="Screenshot 2021-12-07 at 20 59 16" src="https://user-images.githubusercontent.com/664177/145097663-a8f1ebf0-72e7-4acc-a768-b885edd23936.png">
