### ISSUE TITLE
Why `router-view` And `RouterView`

### ISSUE THREAD

**Issue by bekalshenoy** [vuejs/vue-router-next#242]
Why There Are Two Ways To Implement Router View. `router-view` Do Not Require A Import But `RouterView` Required A Import And Specification In Components

**Comment by posva** [comment]
I'm sorry but I don't get your question. Neither requires an import when using vue templates because the component is registered globally: https://vuejs.org/v2/guide/components-registration.html#Name-Casing

Unless you mean something else, in that case **follow the issue reporting guidelines** instead of getting around like you just did by stripping off the whole template and report a bug with a reproduction.

Also, please take 30 seconds to read the _Before you start_ at https://new-issue.vuejs.org/?repo=vuejs/vue-router-next
