### ISSUE TITLE
Add more navigation failure type to handle route component 404  

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue-router-next#462]
### What problem does this feature solve?
What I'm trying to do is showing a specific error message to the users of my app whenever a async route component is not resolved (404). Being able to register global listeners on the router with `router.onError` is great. However, right now, it seems like vue-router is not providing any specific error type for unresolved component, and I would need to do something badass like:
```js
router.onError(err => {
  if (err.message.startsWith("Couldn't resolve component")) {
     // show something
  }
  throw err;
}); 
```

### What does the proposed API look like?
Maybe we could add another builtin type like `NavigationFailureType.unresolvedComponent`
```js
router.onError(err => {
  if (isNavigationFailure(err, NavigationFailureType.unresolvedComponent)) {
     // show something
  }
  throw err;
}); 
```

Can provide PR if it makes sense

**Comment by posva** [comment]
I don't think this is a good idea because `onError` is for unexpected errors, not for navigation failures. There shouldn't be an error resolving a component in normal conditions but if this specifically affects your app you can already do what you are doing or wrap your dynamic imports to do customs checks:

```js
const Some = () => import('./views/Some').then(component => {
  if (!component) ...
})
```

Note the error only appears when the resolved value is falsy, it doesn't catch any rejection or anything. It's only there to gracefully fail. Because of this and because there are different scenarios and this should be handled in userland

**Comment by AlexandreBonaventure** [comment]
sounds good! For the record I ended up using a factory function for creating route components like that:

```js
function createAsyncRouteComponent (loader) {
  return defineAsyncComponent({
    onError (err) {
      // show message
    },
    loader,
  });
}
```
```js
{
    name: 'index',
    path: '/index',
    component: createAsyncRouteComponent(() => import('MyRouteComponent.vue')),
},
```

**Comment by posva** [comment]
Note that `beforeRoute*` in-component guards won't be applied when using an async component as we would have to wait for the component to fully load to eventually trigger the navigation, leaving no time to display the loader
