### ISSUE TITLE
After vite build, Lazy<RouteComponent> has an error

### ISSUE THREAD

**Issue by 0x30** [vuejs/vue-router-next#548]
### Version
4.0.0-rc.1

### Reproduction link
[https://github.com/0x30/vue-router-next-issue](https://github.com/0x30/vue-router-next-issue)

### Steps to reproduce
1. clone
2. npm install
3. npm run dev      --- page is ok
4. npm run build and nginx deploy   ---- page happened error

### What is expected?
no error

### What is actually happening?
I'm not sure if this is the error of vue-route-next or vite
![image](https://user-images.githubusercontent.com/6121524/97159003-2c9df180-17b5-11eb-81f4-ee4a0ff3885e.png)

**Comment by schwarmco** [comment]
it seems to be a problem with the async component loading, see: https://github.com/vitejs/vite/issues/717#issuecomment-705970754

**Comment by 0x30** [comment]
```ts
const AboutMe: RouteRecordRaw = {
  name: "aboutme",
  path: "/about",
  component: defineAsyncComponent({
    loader: () => import("../views/AboutMe")
  })
};
```

This is still a problem, but maybe using defineAsyncComponent can temporarily solve this problem

**Comment by MatthiasGrandl** [comment]
@0x30 this workaround breaks in-component navigation guards. So probably not an option. Only workaround is not to use route splitting for now, which is pretty bad.

**Comment by posva** [comment]
The workaround is to use a variable:

```js
const About = () => import('./page2.vue')
```

instead of 

```js
  { path: '/about', component: () => import('./page2.vue') },
```

FYI: do not use `defineAsyncComponent` with routes, they are not async components, they are raw lazy loaded imports

**Comment by MatthiasGrandl** [comment]
@posva was about to say, that worked for me as well.

**Comment by posva** [comment]
The problem here is that you have both: a static import and a dynamic import of the same module (which should happen) and vite seems to not generate the dynamic file for it:

<img width="529" alt="Screenshot 2020-11-02 at 11 03 24" src="https://user-images.githubusercontent.com/664177/97855444-08816980-1cfb-11eb-9530-1e1c5a1f3772.png">


After removing the line 7 `import About from "./page2.vue"`, it generates the correct bundle:


<img width="524" alt="Screenshot 2020-11-02 at 11 05 34" src="https://user-images.githubusercontent.com/664177/97855640-55fdd680-1cfb-11eb-9444-c6619d2ce3a7.png">

Can you reopen the issue on vite?
