### ISSUE TITLE
useRoute()  problem

### ISSUE THREAD

**Issue by Jmysy** [vuejs/vue-router-next#599]
### Version
4.0.0-rc.3

### Reproduction link
[https://gitee.com/Jmysy/pear-admin-ant](https://gitee.com/Jmysy/pear-admin-ant)

### Steps to reproduce
`const route = useroute();  watch (route, function() { do something })`

### What is expected?
Use useRoute() Api to monitor route changes.

### What is actually happening?
 After the local operation is normal, the interface will be stuck and the CPU will soar, but no error message will be reported

**Comment by Jmysy** [comment]
英文使用翻译, 会有些曲解本意，此处原文来表达我的意思： watch(useRoute(),function(){ }) 此方式监听路由，本地开发调试时没有问题的，打包之后该方式会造成浏览器卡死

**Comment by posva** [comment]
Use `watch(() => route)` or `{ deep: true }` option for the watcher.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
