### ISSUE TITLE
Disable the scroll event triggered automatically after router.push()

### ISSUE THREAD

**Issue by justyeh** [vuejs/vue-router-next#703]
### What problem does this feature solve?
If the page where the router.push method is called has a scrolling behavior, the target page of router.push will automatically trigger a scroll event. In some cases, this will cause a bug. So, how do I disable automatic scrolling after router.push? behavior.

Let me describe the bug:

van-list is a waterfall component, and its automatic loading is achieved by monitoring scroll

The immediate-check parameter is used to determine whether to execute the load event immediately after the page is mounted

Now set its parameter to false

Because vue-router triggered the scroll event, the load event of van-list occurred, which caused an error

vant's document

https://vant-contrib.gitee.io/vant/v3/#/en-US/list

Recurring link

https://codesandbox.io/s/affectionate-kirch-z7ceq?file=/src/views/List.vue

https://z7ceq.csb.app/

### What does the proposed API look like?
Prevent vue-router from automatically triggering the scroll event, or leave the choice to the user

**Comment by posva** [comment]
I don't understand what bug you are trying to report because you are following the wrong template and the reproduction is too much: it should not contain any external lib like vant.

Vue Router will only scroll when returning a position from `scrollBehavior` https://next.router.vuejs.org/guide/advanced/scroll-behavior.html#scroll-behavior. If the problem really comes from vue router, please open a new issue with a boiled down reproduction: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
