### ISSUE TITLE
__FEATURE_PROD_DEVTOOLS__ is not defined - when Vue is externalized

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vue-router-next#792]
### Version
4.0.4

### Reproduction link
[https://github.com/vuejs/vue-router-next](https://github.com/vuejs/vue-router-next)

[The result of the steps below for reference](https://vue-router-next-792.surge.sh/)

### Steps to reproduce
- Add `externals: { vue: 'Vue' },` to the `webpack.config.js` in this repo
- Run the `build:playground` script
- Add the `vue.runtime.global.prod.js` build to the `index.html` in the `playground_dist` folder [0], before the `bundle.js` script
- Serve the playground_dist folder
- Observe the reported error

[0] - e.g. `      <script src="https://unpkg.com/vue@3.0.6/dist/vue.runtime.global.prod.js"></script>`

Optional: Fix the broken npm scripts by putting a space instead of a `.` in `env.prod`?

### What is expected?
`__FEATURE_PROD_DEVTOOLS__` should have a `typeof` guard or be shaken out

*or*

For this to be documented as a flag that should be defined in one's build tool. :)

### What is actually happening?
An undefined variable error

**Comment by posva** [comment]
The steps to reproduce seem unrealistic to me. The build is working with existing configs because the variable is required by Vue itself and therefore configured. If you were bundling Vue as well (instead of using it as an external), you will need the same configuration.
There is a warning in vue's `featureFlags.ts` that points you to https://github.com/vuejs/vue-next/tree/master/packages/vue#bundler-build-feature-flags. I think this is worth adding to Vue docs somewhere to mention feature flags. Can you open an issue in docs-next?

In practice, it doesn't make sense to bundle vue-router but not vue so I don't think that warning is worth duplicating.

> Optional: Fix the broken npm scripts by putting a space instead of a . in env.prod?

I don't understand, there is no such file.

**Comment by pearofducks** [comment]
@posva - the "Optional" refers to package.json scripts:

```
    "build:playground": "webpack --env.prod",
    "build:e2e": "webpack --env.prod --config e2e/webpack.config.js",
```

Those commands fail 

`[webpack-cli] Error: Unknown option '--env.prod'`

---

Could you clarify, you don't think it's realistic to externalize Vue but not Vue Router?

If one is always externalizing Vue, this variable would never need to be set, and introducing Vue Router would then suddenly require defining this string.
