### ISSUE TITLE
Page's animation on enter active skips animation frame near the end when the page is refreshed via the refresh button of the browser 

### ISSUE THREAD

**Issue by sanjade** [vuejs/vue-router-next#827]
### Version
4.0.5

### Reproduction link
[https://github.com/sanjade/vue3-bug](https://github.com/sanjade/vue3-bug)

### Steps to reproduce
```
git clone https://github.com/sanjade/vue3-bug
cd vue3-bug
yarn
yarn dev
```
Navigate to /modal. Now refresh this `/modal` page with the refresh button of browser. You can see when the animation is about to end, the animation suddenly jumps to the end. Here's a video example of this issue: https://youtu.be/Q6Gy_E5ptzI

**MAKE SURE YOU USE THE REFRESH BUTTON OF BROWSER AS SHOWN IN THE YT VIDEO. If you refresh via browser URL then the animation is smooth**

### What is expected?
I expect a fluid animation

### What is actually happening?
The animation frame is skipped near the end of initial animation

**Comment by posva** [comment]
This is unrelated to Vue Router or Vue, it's just the browser skipping frames probably because it's busy doing something else. For instance, I don't experience any skip. You might have an extension slowing down your page.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
