### ISSUE TITLE
mock a pending component for the time to resolve beforeEach hook

### ISSUE THREAD

**Issue by germsb** [vuejs/vue-router-next#830]
### Version
4.0.5

Vue Suspense component dont return fallback when vue-router is locked by a promise in beforeEach hook.
Maybe the router could provide a mock pending component the time to be able to return a route?

```html
<router-view v-slot="{component}">
        <Suspense>
            <template #default>
                <div>
                    <component :is="component" />
                </div>
            </template>
            <template #fallback>
                <span>Loading...</span>
            </template>
        </Suspense>
    </router-view>
```

**Comment by posva** [comment]
You likely need a `:timeout="0"` in your suspense component
Proper integration with suspense is yet to come.

**Comment by germsb** [comment]
Thank you for timeout, but that doesn't help in this case, I had already tested
Disappointed that it is closed so quickly.
Is duplicate with other issue?  Is there any discussion to track?

**Comment by germsb** [comment]
> Proper integration with suspense is yet to come.

@posva Any news on this ?

**Comment by posva** [comment]
It was closed because it didn't follow the guidelines. Other than that, this has been discussed multiple times in other issues over at vue-next and they also usually appear linked here. Looking for suspense fallback in issues yields the issues with different explanations.

That being said, Suspense is still experimental, and a few necessary changes are still needed in core for it to become stable and get a better integration with vue-router (which has also been said in other issues already)
