### ISSUE TITLE
Dynamic Routing miss history.state

### ISSUE THREAD

**Issue by pspaczek** [vuejs/vue-router-next#866]
### Version
4.0.6

### Reproduction link
[https://github.com/pspaczek/router](https://github.com/pspaczek/router)

### Steps to reproduce
1. click PatientAge
3. click browser back
4. check the console and find the error
[afterEach] location: http://localhost:8080/, state: {"back":"/","current":"/","forward":null,"replaced":false,"position":2,"scroll":null}
5. click browser back (still you have Message, and after each has a right history.state)
[afterEach] location: http://localhost:8080/, state: {"back":null,"current":"/","forward":"/","position":1,"replaced":true,"scroll":{"left":0,"top":0}}

### What is expected?
1. click PatientAge
3. click browser back
4. has console without error
5. click browser back and no duplication of Message 

### What is actually happening?
between beforeResolve and afterEach something broke the history.state whe you use browser back

---
I want to use Dynamic Routing to keep the only actual route in the router. It's works until you use the browser back.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

A few recommendations:

> I want to use Dynamic Routing to keep the only actual route in the router.

Don't keep **only** the active route, the router is not meant to be used like that. You can add routes as you need them but it makes no sense to remove them if the user can go back and reach the existing route. **It particular, don't remove the route you are navigating away from when redirecting**:

```js
  if (!hasNecessaryRoute(to)) {
    if(from.name) {
      // don't remove this route 🙅‍♂️
	  // it is needed by the `return to.fullPath` to
	  // know where we were coming from
      router.removeRoute(from.name);
    }
    router.addRoute(generateRoute(to));
    return to.fullPath
  }
```

Don't use the properties added by the router to `history.state`, **they are not public API**, that's why they are undocumented. The router uses them to function properly
