### ISSUE TITLE
When I use keepAlive,  nextTick fails in router.afterEach 

### ISSUE THREAD

**Issue by wmb0412** [vuejs/vue-router-next#979]
### Version
4.0.8

### Reproduction link
[https://jsfiddle.net/x6jgbhtf/11/](https://jsfiddle.net/x6jgbhtf/11/)

### Steps to reproduce
1. To  foo page.
2.To  bar page.
3. To foo page . 

### What is expected?
i want to get dom

### What is actually happening?
When I go to foo page the second time,document,querySelector('#foo') is null  in router.afterEach.

**Comment by posva** [comment]
This is because you have a transition so the element appears afterwards:

```html
<transition @after-enter="doSomething">
```

`doSomething` will get the element (https://v3.vuejs.org/guide/transitions-enterleave.html#javascript-hooks)

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
